'use client';

import { useState } from 'react';

export default function LoginPage() {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [isLoading, setIsLoading] = useState(false);
        const [error, setError] = useState('');

          const handleSubmit = async (e: React.FormEvent) => {
              e.preventDefault();
                  setIsLoading(true);
                      setError('');

                          try {
                                console.log('Logging in with:', { email, password });
                                      await new Promise((resolve) => setTimeout(resolve, 1000));
                                          } catch (err) {
                                                setError('Email atau password salah. Coba lagi.');
                                                    } finally {
                                                          setIsLoading(false);
                                                              }
                                                                };

                                                                  return (
                                                                      <div className="flex min-h-screen items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-900">
                                                                            <div className="w-full max-w-md space-y-8 rounded-xl bg-white p-8 shadow-md dark:bg-gray-800">
                                                                                    <div>
                                                                                              <h2 className="mt-2 text-center text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
                                                                                                          Masuk ke Akun
                                                                                                                    </h2>
                                                                                                                              <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
                                                                                                                                          Masukkan email dan password kamu untuk melanjutkan.
                                                                                                                                                    </p>
                                                                                                                                                            </div>

                                                                                                                                                                    {error && (
                                                                                                                                                                              <div className="rounded-md bg-red-50 p-4 text-sm text-red-600 dark:bg-red-900/30 dark:text-red-400">
                                                                                                                                                                                          {error}
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                            )}

                                                                                                                                                                                                                    <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
                                                                                                                                                                                                                              <div className="space-y-4 rounded-md">
                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                        <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                                                                                                                                                                                                                                                                        Email
                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                    id="email"
                                                                                                                                                                                                                                                                                                                                    name="email"
                                                                                                                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                    className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white sm:text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="nama@domain.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white sm:text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={isLoading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="flex w-full justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {isLoading ? 'Memproses...' : 'Masuk'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
